version: "3.4"

services:

    nginx:
        build: ./nginx
        ports:
            - "80:80"
        container_name: nginx_jf
        restart: always
        volumes:
            - ./files/front:/var/www/html
        depends_on:
            - php
            - db
        networks:
            - webserver
            - backend

    php:
        image: php:7-fpm
        container_name: php_jf
        restart: always
        volumes:
            - ./files/front:/var/www/html
        networks:
            - backend
            - database

    db:
        build: ./db
        container_name: db_jf
        restart: always
        volumes:
            - ./files/db:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=YES
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
        networks:
            - database

networks:
    webserver:
    backend:
    database:
